@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiTXVyaWxvQGdtYWlsLmNvbSIsIm5hbWUiOiJNdXJpbG8iLCJpYXQiOjE3NjIwMjM2MjAsImV4cCI6MTc2MjA1MjQyMH0.tzFUL-N6yRhsnd6SuZOg65RtpMYWE3E4V5H9LwMt_jg

### criando um client
POST http://localhost:3000/clients HTTP/1.1
content-type: application/json

{
    "name" : "Marcius",
    "document" : "111.222.333.44",
    "cep" : "12345-678",
    "phone" : "16 12345-6789",
    "email" : "marcius@gmail.com",
    "address" : "Rua Epscopal",
    "number" : 700,
    "neighborhood" : "Centro",
    "state" : "São Paulo",
    "city" : "São Carlos",
    "isActive" : true,
    "userId" : 1
    
}
### Lendo os clients
GET http://localhost:3000/clients HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Lendo os clients lpor id
GET http://localhost:3000/clients/1 HTTP/1.1
content-type: application/json

### Lendo clients e name
GET http://localhost:3000/clients?name=Marcius HTTP/1.1
content-type: application/json

### Lendo clients, name e document
GET http://localhost:3000/clients?name=Marcius&document=111.222.333.44 HTTP/1.1
content-type: application/json

### Lendo clients, name, document e cep
GET http://localhost:3000/clients?name=Marcius&document=111.222.333.44&cep=12345-678 HTTP/1.1
content-type: application/json

### Lendo clients, name, document, cep e phone
GET http://localhost:3000/clients?name=Marcius&document=111.222.333.44&cep=12345-678&phone=16-12345-6789 HTTP/1.1
content-type: application/json

### Lendo clients, name, document, cep, phone e email
GET http://localhost:3000/clients?name=Marcius&document=111.222.333.44&cep=12345-678&phone=16-12345-6789&email=marcius@gmail.com HTTP/1.1
content-type: application/json

### Lendo clients, name, document, cep, phone, email e addres
GET http://localhost:3000/clients?name=Marcius&document=111.222.333.44&cep=12345-678&phone=16-12345-6789&email=marcius@gmail.com&address=Rua Epscopal HTTP/1.1
content-type: application/json

### Lendo clients, name, document, cep, phone, email, address e number
GET http://localhost:3000/clients?name=Marcius&document=111.222.333.44&cep=12345-678&phone=16-12345-6789&email=marcius@gmail.com&address=Rua Epscopal&number=700 HTTP/1.1
content-type: application/json

### Lendo clients, name, document, cep, phone, email, address, number e neighborhood
GET http://localhost:3000/clients?name=Marcius&document=111.222.333.44&cep=12345-678&phone=16-12345-6789&email=marcius@gmail.com&address=Rua Epscopal&number=700&neighborhood=Centro HTTP/1.1
content-type: application/json

### Lendo clients, name, document, cep, phone, email, address, number, neighborhood e state
GET http://localhost:3000/clients?name=Marcius&document=111.222.333.44&cep=12345-678&phone=16 12345-6789&email=marcius@gmail.com&address=Rua Epscopal&number=700&neighborhood=Centro&state=São Paulo HTTP/1.1
content-type: application/json

### Lendo clients, name, document, cep, phone, email, address, number, neighborhood, state e city
GET http://localhost:3000/clients?name=Marcius&document=111.222.333.44&cep=12345-678&phone=16-12345-6789&email=marcius@gmail.com&address=Rua Epscopal&number=700&neighborhood=Centro&state=São Paulo&city=São Carlos HTTP/1.1
content-type: application/json

### Lendo clients, name, document, cep, phone, email, address, number, neighborhood, state, city e isActive
GET http://localhost:3000/clients?name=Marcius&document=111.222.333.44&cep=12345-678&phone=16-12345-6789&email=marcius@gmail.com&address=Rua Epscopal&number=700&neighborhood=Centro&state=São Paulo&city=São Carlos&isActive=true HTTP/1.1
content-type: application/json

### Atualizando os clients por id
DELETE   http://localhost:3000/clients/1 HTTP/1.1
content-type: application/json

### Atualizando os clients por id
PUT  http://localhost:3000/clients/1 HTTP/1.1
content-type: application/json

{
    "name" : "Murilo",
    "document" : "111.922.393.44",
    "cep" : "12345-000"    
}

