### criando um client
POST http://localhost:3000/clients HTTP/1.1
content-type: application/json

{
    "name" : "Marcius",
    "document" : "111.222.333.44",
    "cep" : "12345-678",
    "phone" : "16 12345-6789",
    "email" : "marcius@gmail.com",
    "address" : "Rua Epscopal",
    "number" : 700,
    "neighborhood" : "Centro",
    "state" : "São Paulo",
    "city" : "São Carlos",
    "isActive" : true,
    "userId" : 1
    
}
###criando um usuario
GET http://localhost:3000/clients HTTP/1.1
content-type: application/json


