### Criando uma order

POST http://localhost:3000/orders HTTP/1.1
content-Type: application/json

{
    "servicePrice" : 29,
    "productPrice" : 10,
    "userId" : 1,
    "serviceId" : 1,
    "clientId" : 1
}

### Ler todas orders
GET http://localhost:3000/orders HTTP/1.1
content-Type: application/json

### Ler saleprice
GET http://localhost:3000/orders?saleMax=30&saleMin=20 HTTP/1.1
content-Type: application/json

### Ler saleprice e servicePrice
GET http://localhost:3000/orders?salePrice=20&servicePrice=29 HTTP/1.1
content-Type: application/json

### Ler saleprice, servicePrice e productPrice
GET http://localhost:3000/orders?salePrice=20&servicePrice=29&productPrice=10 HTTP/1.1
content-Type: application/json

### Ler um order pelo id
GET http://localhost:3000/orders/10 HTTP/1.1
content-Type: application/json


### Deletar orders pelo id
DELETE http://localhost:3000/orders/4 HTTP/1.1
content-Type: application/json


### Atualizar orders pelo id

PUT http://localhost:3000/orders/1 HTTP/1.1
content-Type: application/json

{
    "salePrice" : 24,
    "servicePrice" : 30,
    "productPrice" : 14
}