@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiTXVpbDBAeWFob28uY29tIiwibmFtZSI6Ik11cmlsbyIsImlhdCI6MTc1OTk1NTM1MiwiZXhwIjoxNzU5OTg0MTUyfQ.fuebJu7sJmD3zpRoo4RydAqPtp7zvP0e_rtRdGNIu_8

### Criando um product
POST http://localhost:3000/products HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "name" : "MSI B450",
    "category" : "Placa Mãe",
    "description" : "127v",
    "salesUnit" : "UN", 
    "purchasePrice" : 10, 
    "salePrice" : 20, 
    "observations" : "Azul",
    "isActive" : true,
}

### ler todos os product
GET  http://localhost:3000/products HTTP/1.1
content-type: application/json

### ler products e name
GET  http://localhost:3000/products?name=MSI B450 HTTP/1.1
content-type: application/json

### ler products, name e category
GET  http://localhost:3000/products?name=MSIB450&category=placa Mãe HTTP/1.1
content-type: application/json

### ler products, name, category e purchasePrice
GET  http://localhost:3000/products?name=MSI B450&category=placa Mãe&purchasePrice=10 HTTP/1.1
content-type: application/json

### ler products, name, category, purchasePrice e salePrice
GET  http://localhost:3000/products?name=MSI B450&category=placa Mãe&purchasePrice=10&salePrice=20 HTTP/1.1
content-type: application/json

### ler products, name, category, purchasePrice, salePrice isActive
GET  http://localhost:3000/products?name=MSI B450&category=placa Mãe&purchasePrice=10&salePrice=20&isActive HTTP/1.1
content-type: application/json

### Deletar todos os product
DELETE  http://localhost:3000/products/1 HTTP/1.1
content-type: application/json

### Atualizando todos os product
PUT  http://localhost:3000/products/1 HTTP/1.1
content-type: application/json

{
    "name" : "MSI B550",
    "category" : "Placa Mãe",
    "description" : "Bivolt",
    "purchasePrice" : 10, 
    "salePrice" : 300
}