### Criando um product
POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "name" : "MSI B450",
    "category" : "Placa Mãe",
    "description" : "127v",
    "salesUnit" : "UN", 
    "purchasePrice" : 10, 
    "salePrice" : 20, 
    "observations" : "Azul",
    "isActive" : true,
    "userId" : 1

}

### ler todos os product
GET  http://localhost:3000/products HTTP/1.1
content-type: application/json

### ler products e name
GET  http://localhost:3000/products?name=MSIB450 HTTP/1.1
content-type: application/json

### ler products, name e category
GET  http://localhost:3000/products?name=MSIB450&category=placaMãe HTTP/1.1
content-type: application/json

### ler products, name, category e purchasePrice
GET  http://localhost:3000/products?name=MSIB450&category=placaMãe&purchasePrice=10 HTTP/1.1
content-type: application/json

### ler products, name, category, purchasePrice e salePrice
GET  http://localhost:3000/products?name=MSIB450&category=placaMãe&purchasePrice=10&salePrice=20 HTTP/1.1
content-type: application/json

### ler products, name, category, purchasePrice, salePrice e isActive
GET  http://localhost:3000/products?name=MSIB450&category=placaMãe&purchasePrice=10&salePrice=20&isActive=true HTTP/1.1
content-type: application/json
