### Criando um service
POST http://localhost:3000/services HTTP/1.1
content-type: application/json

{
    "nameService" : "testee",
    "price" : 20, 
    "description" : "blabla", 
    "observations" : "blabla2", 
    "isActive" : true, 
    "userId" : 1
}

### Ler todas services

GET http://localhost:3000/services HTTP/1.1
Content-type: application/json