###Criando os shops
POST http://localhost:3000/shops HTTP/1.1
content-type: application/json

{
    "orderId": 1, 
    "productId": 1, 
    "amount": 1, 
    "salePrice" : 30
}

### Ler Todos os Shops
GET http://localhost:3000/shops HTTP/1.1
Content-Type: application/json

### Ler o price
GET http://localhost:3000/shops?salePrice=30 HTTP/1.1
Content-Type: application/json

### Ler o price e amount
GET http://localhost:3000/shops?salePrice=30&amount=1 HTTP/1.1
Content-Type: application/json

### Ler o price, amout e id do product
GET http://localhost:3000/shops?salePrice=30&amount=1&productId=1 HTTP/1.1
Content-Type: application/json

### atualizando os Shops
DELETE   http://localhost:3000/shops/1 HTTP/1.1
Content-Type: application/json

### atualizando os Shops
PUT  http://localhost:3000/shops/1 HTTP/1.1
Content-Type: application/json