### Criando um Usuario
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "email" : "murilo@gmail.com",
    "password" : "12345678",
    "document" : "111.222.333-44",
    "phone" : "16 99999-9999",
    "birth" : "1970-01-01T00:00:00.000Z",
    "signature" : "Basic",
    "isActive" : true
}

### Ler Todos os Usuarios

GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json